### ISSUE TITLE
[Bug] `scikit_learn` is identified as a required package for `transformer`

### ISSUE THREAD

**Issue by Fred-Fan** [IBM/import-tracker#73]
## Describe the bug

When getting the required package for `transformer` in watson nlp, `scikit_learn` is identified. But it seems sklean is just an optional package for `transformer.data` module, referring to the [code](https://github.com/huggingface/transformers/blob/da1af21dbbc48ad4f6f0b27635cd3993ddc22b55/src/transformers/data/metrics/__init__.py#L20) and we actually don't use  `transformer.data` module. 
Can we remove `sklearn` from the required packages if we don't use `data` module? 
Please see more details in this issue https://github.ibm.com/ai-foundation/watson-nlp-tracker/issues/4153

## Platform

Please provide details about the environment you are using, including the following:

-   Interpreter version:
-   Library version:

## Sample Code

[getmodule.ipynb.zip](https://github.com/IBM/import-tracker/files/12525949/getmodule.ipynb.zip)
The attached zip contains the .ipynb file I used to trace the modules. It shows how import_tracker get `sklearn` from `transformer`

## Expected behavior

`sklearn` will no longer be the required package for transformed if data module is not used

## Observed behavior

What you see happening (error messages, stack traces, etc...)

**Comment by Fred-Fan** [comment]
Meanwhile, I saw `setup_tools.parse_requirements` has an argument `keep_optional` which enable the user to keep the modules they want. But it does not fit our case. I am wondering if we could have another argument, e.g. `remove_optional` which enables us to remove the packages.

**Comment by Fred-Fan** [comment]
@gkumbhat Hi,Gaurav, since you are aware of this case and have triaged it, I will assign this case to you first. Please help trouble shoot this case or transfer it to anyone else you think is a better fit.  Thanks a lot

**Comment by Fred-Fan** [comment]
Another question, it seems `import-tracker` will get the deps from A not just B if we run `from A import B`. So even if we don't use `import transformer` but `from transformer import XXX`, it still get all deps from `transformer`

**Comment by gabe-l-hart** [comment]
>Another question, it seems import-tracker will get the deps from A not just B if we run from A import B. So even if we don't use import transformer but from transformer import XXX, it still get all deps from transformer

This actually has to do with how the python import mechanism works. When you call `from A import B`, it's functionally equivalent to `import A; B = A.B`. As such, _all_ of `A` will be imported before the `getattr(A, "B")` happens.

**Comment by Fred-Fan** [comment]
I see. Then it seems we have to import all modules from `transformer` since we have a lot of import like:
```
from transformers import (
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoModelForTokenClassification,
    AutoTokenizer,
    DataCollatorForTokenClassification,
    DataCollatorWithPadding,
    EvalPrediction,
    HfArgumentParser,
    PreTrainedTokenizerFast,
    Trainer,
    TrainingArguments,
    set_seed,)
```
But is it possible we can skip the packages like `sklearn` if it is a conditional import?

**Comment by gabe-l-hart** [comment]
I think the root of this is that [the logic for identifying optional dependencies](https://github.com/IBM/import-tracker/blob/main/import_tracker/import_tracker.py#L457) relies on `try/except` rather than an `if` which is how it's implemented in `transformers` per your link. I'll need to think a bit about this since we'd need some pretty deep parsing to identify whether an `if` condition like this is functionally acting as a guard for an optional dependency.

One possible solution would be to allow the caller to somehow hint that certain packages are expected to be optional. Another option would be to attempt to parse the package contents for optional metadata [like we do to get the installed names](https://github.com/IBM/import-tracker/blob/main/import_tracker/setup_tools.py#L247)

**Comment by gabe-l-hart** [comment]
So there's actually a little more nuance to the `from A import B` and it has to do with how `A` has structured its imports. If `A` uses _proactive_ imports (inside `A/__init__.py` doing `from . import C`) then doing `from A import B` will implicitly import `A.C` as well. If, however, `A/__init__.py` does NOT proactively import `C` inside of `A`, then it won't.

**Comment by gabe-l-hart** [comment]
>But is it possible we can skip the packages like sklearn if it is a conditional import?

Yes, this is definitely possible, BUT automatically catching it will be really tough. The problem is that it's quite hard to cover all the different ways that a library might choose to manage optional dependencies. The only one that `import-tracker` attempts to find automatically is:

```py
try:
    import foo
    HAVE_FOO = True
except ImportError:
    HAVE_FOO = False
```

In `transformers`, it looks like they centralize all of this logic in [import_utils.py](https://github.com/huggingface/transformers/blob/da1af21dbbc48ad4f6f0b27635cd3993ddc22b55/src/transformers/utils/import_utils.py#L117) and use `importlib.find_spec` rather than a `try/except`.

**Comment by Fred-Fan** [comment]
I see...I saw you already have `keep_optional` , is it possible for import_tracker to have an argument like `remove_optional` so that we can define which package we would like to remove from one module's deps?  It would be easier for us to manually hack the deps with code. Otherwise we need to hard code in the `setup.py
`

**Comment by Fred-Fan** [comment]
@gabe-l-hart Hi, is there any thoughts for the fix?

**Comment by Fred-Fan** [comment]
@gabe-l-hart Are there any updates?

**Comment by Fred-Fan** [comment]
Close since it is solved
